# Generated by Django 6.0.6 on 2026-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messexpense',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
